# Generated by Django 3.2.9 on 2021-11-28 22:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('description', models.TextField(max_length=1000)),
                ('image', models.ImageField(upload_to='photo/%Y/%m/%d/')),
                ('lodging_type', models.CharField(choices=[('F', 'Flat'), ('HST', 'Hostel'), ('HS', 'House'), ('HR', 'HotelRoom')], default='HR', max_length=3)),
                ('places', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1)),
                ('night_price', models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Night price')),
                ('isWifi', models.BooleanField(default=True, verbose_name='WiFi')),
                ('isConditioner', models.BooleanField(default=False, verbose_name='Conditioner')),
                ('isKitchen', models.BooleanField(default=False, verbose_name='Kitchen')),
                ('isBreakfast', models.BooleanField(default=False, verbose_name='Breakfast')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('isPublished', models.BooleanField(default=True, verbose_name='Published')),
            ],
        ),
    ]
